version: '3.1'
services:
  proxy:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./ssl:/etc/ssl/nginx/:ro
      - ./config:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - 16_lolo
networks:
  16_lolo:
    external: true
    
