version: '3.1'
services:
  imgenv:
    image: jayantrpathak/msn:16.0
    ports:
      - "6029:8069"
      - "6039:8072"
    volumes:
      - dist-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    networks:
      - 16_lolo
volumes:
  dist-web-data:

secrets:
  postgresql_password:
    file: ../odoo_pg_pass.txt
networks:
  16_lolo:
    external: true
