version: '3.1'
services:
  modulesnow:
    image: odoo:16.0
    ports:
      - "8009:8069"
      - "8019:8072"
    volumes:
      - modulesnow-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    networks:
      - 16_lolo
volumes:
  modulesnow-web-data:

secrets:
  postgresql_password:
    file: ../odoo_pg_pass.txt
networks:
  16_lolo:
    external: true
